In [1]:
## import libraries
import pandas as pd 
import os

In [3]:
path = r"C:\Users\SVS\Desktop\ML Project\data\raw"
os.listdir(path)

['crop-wise-area-production-yield.csv',
 'crop-wise-irrigated-area.csv',
 'daily-rainfall-data-district-level.csv',
 'soil-nutrient-analysis.csv',
 'sources-of-irrigation.csv']

In [4]:
path = r"C:\Users\SVS\Desktop\ML Project\data\raw"

apy = pd.read_csv(path + r"\crop-wise-area-production-yield.csv")

rainfall = pd.read_csv(path + r"\daily-rainfall-data-district-level.csv")

irrigation = pd.read_csv(path + r"\crop-wise-irrigated-area.csv")

irrigation_sources = pd.read_csv(path + r"\sources-of-irrigation.csv")

soil = pd.read_csv(path + r"\soil-nutrient-analysis.csv")

In [6]:
## crop yield and production
apy.shape

(455359, 16)

In [7]:
apy.head()

,id,year,state_name,state_code,district_name,district_code,crop_name,crop_code,crop_type,season,area,area_unit,production,production_unit,yield,yield_unit
0,0,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Arhar/Tur,202.0,Pulses,Kharif,21400.0,Hectare,2600.0,Tonnes,0.121,Tonnes/Hectare
1,1,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Bajra,103.0,Cereals,Kharif,1400.0,Hectare,500.0,Tonnes,0.357,Tonnes/Hectare
2,2,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Castor Seed,1002.0,Oilseeds,Kharif,1000.0,Hectare,100.0,Tonnes,0.100,Tonnes/Hectare
3,3,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Cotton(Lint),1101.0,Fiber Crops,Kharif,7300.0,Hectare,9400.0,Tonnes,1.288,Tonnes/Hectare
4,4,1997-1998,Andhra Pradesh,28,Ananthapuramu,502,Dry Chillies,502.0,Spices,Kharif,3700.0,Hectare,7100.0,Tonnes,1.919,Tonnes/Hectare

In [8]:
apy.columns

Index(['id', 'year', 'state_name', 'state_code', 'district_name',
       'district_code', 'crop_name', 'crop_code', 'crop_type', 'season',
       'area', 'area_unit', 'production', 'production_unit', 'yield',
       'yield_unit'],
      dtype='object')

In [9]:
apy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455359 entries, 0 to 455358
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               455359 non-null  int64
 1   year             455359 non-null  object
 2   state_name       455359 non-null  object
 3   state_code       455359 non-null  int64
 4   district_name    455359 non-null  object
 5   district_code    455359 non-null  int64
 6   crop_name        455359 non-null  object
 7   crop_code        455338 non-null  float64
 8   crop_type        455359 non-null  object
 9   season           455359 non-null  object
 10  area             455359 non-null  float64
 11  area_unit        455359 non-null  object
 12  production       450350 non-null  float64
 13  production_unit  455359 non-null  object
 14  yield            455359 non-null  float64
 15  yield_unit       455359 non-null  object
dtypes: float64(4), int64(3), object(9)
memory usage: 55.6+ MB

In [10]:
apy.isnull().sum()

id                    0
year                  0
state_name            0
state_code            0
district_name         0
district_code         0
crop_name             0
crop_code            21
crop_type             0
season                0
area                  0
area_unit             0
production         5009
production_unit       0
yield                 0
yield_unit            0
dtype: int64

In [11]:
apy.duplicated().sum()

np.int64(0)

In [36]:
apy["state_name"].unique()

array(['Andhra Pradesh', 'Assam', 'Arunachal Pradesh', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Jammu And Kashmir',
       'Jharkhand', 'Karnataka', 'Kerala', 'Maharashtra', 'Ladakh',
       'Madhya Pradesh', 'Nagaland', 'Odisha', 'Manipur', 'Meghalaya',
       'Mizoram', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
       'Chandigarh', 'Himachal Pradesh', 'Puducherry',
       'The Dadra And Nagar Haveli And Daman And Diu', 'Tripura',
       'Andaman And Nicobar Islands'], dtype=object)

In [37]:
apy["district_name"].nunique()

737

In [38]:
apy["crop_name"].nunique()

115

In [39]:
apy["season"].unique()

array(['Kharif', 'Rabi', 'Total', 'Whole Year', 'Autumn', 'Summer',
       'Winter'], dtype=object)

In [12]:
## Rainfall 
rainfall.shape

(3577399, 10)

In [13]:
rainfall.head()

,id,date,state_code,state_name,district_code,district_name,actual,rfs,normal,deviation
0,0,2009-04-01,35,Andaman And Nicobar Islands,603,Nicobars,NaN,0.0,0.3,NaN
1,1,2009-04-01,35,Andaman And Nicobar Islands,632,North And Middle Andaman,NaN,0.0,1.4,NaN
2,2,2009-04-01,35,Andaman And Nicobar Islands,602,South Andamans,NaN,NaN,NaN,NaN
3,3,2009-04-02,35,Andaman And Nicobar Islands,603,Nicobars,NaN,0.0,0.1,NaN
4,4,2009-04-02,35,Andaman And Nicobar Islands,632,North And Middle Andaman,NaN,0.0,1.0,NaN

In [14]:
rainfall.columns

Index(['id', 'date', 'state_code', 'state_name', 'district_code',
       'district_name', 'actual', 'rfs', 'normal', 'deviation'],
      dtype='object')

In [15]:
rainfall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3577399 entries, 0 to 3577398
Data columns (total 10 columns):
 #   Column         Dtype
---  ------         -----
 0   id             int64
 1   date           object
 2   state_code     int64
 3   state_name     object
 4   district_code  int64
 5   district_name  object
 6   actual         float64
 7   rfs            float64
 8   normal         float64
 9   deviation      float64
dtypes: float64(4), int64(3), object(3)
memory usage: 272.9+ MB

In [16]:
rainfall.isnull().sum()

id                     0
date                   0
state_code             0
state_name             0
district_code          0
district_name          0
actual            139887
rfs                41812
normal            665655
deviation        1145632
dtype: int64

In [17]:
rainfall.duplicated().sum()

np.int64(0)

In [18]:
## crop wisse irrigated area
irrigation.shape

(605000, 13)

In [19]:
irrigation.head()

,id,year,state_name,state_code,district_name,district_code,food_category,crop_type,sub_crop_type,crop_name,crop_code,season,area
0,0,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Food Crop,Cereals & Millets,Cereals & Millets,Bajra,103.0,NaN,NaN
1,1,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Food Crop,Cereals & Millets,Cereals & Millets,Barley,107.0,NaN,NaN
2,2,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Food Crop,Cereals & Millets,Cereals & Millets,Jowar,102.0,Kharif,NaN
3,3,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Food Crop,Cereals & Millets,Cereals & Millets,Jowar,102.0,Rabi,NaN
4,4,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Food Crop,Cereals & Millets,Cereals & Millets,Jowar,102.0,Summer,NaN

In [20]:
irrigation.columns

Index(['id', 'year', 'state_name', 'state_code', 'district_name',
       'district_code', 'food_category', 'crop_type', 'sub_crop_type',
       'crop_name', 'crop_code', 'season', 'area'],
      dtype='object')

In [21]:
irrigation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605000 entries, 0 to 604999
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             605000 non-null  int64
 1   year           605000 non-null  object
 2   state_name     605000 non-null  object
 3   state_code     605000 non-null  int64
 4   district_name  603280 non-null  object
 5   district_code  603280 non-null  float64
 6   food_category  605000 non-null  object
 7   crop_type      605000 non-null  object
 8   sub_crop_type  605000 non-null  object
 9   crop_name      605000 non-null  object
 10  crop_code      605000 non-null  float64
 11  season         196625 non-null  object
 12  area           191189 non-null  float64
dtypes: float64(3), int64(2), object(8)
memory usage: 60.0+ MB

In [22]:
irrigation.isnull().sum()

id                    0
year                  0
state_name            0
state_code            0
district_name      1720
district_code      1720
food_category         0
crop_type             0
sub_crop_type         0
crop_name             0
crop_code             0
season           408375
area             413811
dtype: int64

In [23]:
irrigation.duplicated().sum()

np.int64(0)

In [24]:
## Source of Irrigation 
irrigation_sources.shape

(181500, 10)

In [25]:
irrigation_sources.head()

,id,year,state_name,state_code,district_name,district_code,irrigated_area_type,area_classification,area_sub_classification,irrigated_area
0,0,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Gross Irrigated Area,Canal,Government,NaN
1,1,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Gross Irrigated Area,Canal,Private,NaN
2,2,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Gross Irrigated Area,Other Source,Other Source,NaN
3,3,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Gross Irrigated Area,Tank,Tank,NaN
4,4,1998-1999,Andaman And Nicobar Islands,35,Nicobars,603.0,Gross Irrigated Area,Well,Other Well,NaN

In [26]:
irrigation_sources.columns

Index(['id', 'year', 'state_name', 'state_code', 'district_name',
       'district_code', 'irrigated_area_type', 'area_classification',
       'area_sub_classification', 'irrigated_area'],
      dtype='object')

In [27]:
irrigation_sources.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181500 entries, 0 to 181499
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       181500 non-null  int64
 1   year                     181500 non-null  object
 2   state_name               181500 non-null  object
 3   state_code               181500 non-null  int64
 4   district_name            180984 non-null  object
 5   district_code            180984 non-null  float64
 6   irrigated_area_type      181500 non-null  object
 7   area_classification      181500 non-null  object
 8   area_sub_classification  181500 non-null  object
 9   irrigated_area           100110 non-null  float64
dtypes: float64(2), int64(2), object(6)
memory usage: 13.8+ MB

In [28]:
irrigation_sources.isnull().sum()

id                             0
year                           0
state_name                     0
state_code                     0
district_name                516
district_code                516
irrigated_area_type            0
area_classification            0
area_sub_classification        0
irrigated_area             81390
dtype: int64

In [29]:
irrigation_sources.duplicated().sum()

np.int64(0)

In [30]:
## Soil Nutrient 
soil.shape

(10853209, 14)

In [31]:
soil.head()

,id,year,state_name,state_code,district_name,district_code,block_name,block_code,village_name,village_code,nutrient_type,nutrient_name,nutrient_level,value
0,3107023,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Copper,Deficient,0
1,3107024,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Copper,Sufficient,85
2,3107025,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Iron,Deficient,0
3,3107026,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Iron,Sufficient,85
4,3107027,2023-24,Uttarakhand,5,Udham Singh Nagar,56,Rudrapur,439,Malsi,55943,Micro,Manganese,Deficient,2

In [32]:
soil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10853209 entries, 0 to 10853208
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   id              int64
 1   year            object
 2   state_name      object
 3   state_code      int64
 4   district_name   object
 5   district_code   int64
 6   block_name      object
 7   block_code      int64
 8   village_name    object
 9   village_code    int64
 10  nutrient_type   object
 11  nutrient_name   object
 12  nutrient_level  object
 13  value           int64
dtypes: int64(6), object(8)
memory usage: 1.1+ GB

In [33]:
soil.isnull().sum()

id                0
year              0
state_name        0
state_code        0
district_name     0
district_code     0
block_name        0
block_code        0
village_name      0
village_code      0
nutrient_type     0
nutrient_name     0
nutrient_level    0
value             0
dtype: int64

In [34]:
soil.duplicated().sum()

np.int64(0)

In [40]:
print("APY:")
print(apy.columns.tolist())

print("\nRainfall:")
print(rainfall.columns.tolist())

print("\nIrrigation:")
print(irrigation.columns.tolist())

print("\nIrrigation Sources:")
print(irrigation_sources.columns.tolist())

print("\nSoil:")
print(soil.columns.tolist())

APY:
['id', 'year', 'state_name', 'state_code', 'district_name', 'district_code', 'crop_name', 'crop_code', 'crop_type', 'season', 'area', 'area_unit', 'production', 'production_unit', 'yield', 'yield_unit']

Rainfall:
['id', 'date', 'state_code', 'state_name', 'district_code', 'district_name', 'actual', 'rfs', 'normal', 'deviation']

Irrigation:
['id', 'year', 'state_name', 'state_code', 'district_name', 'district_code', 'food_category', 'crop_type', 'sub_crop_type', 'crop_name', 'crop_code', 'season', 'area']

Irrigation Sources:
['id', 'year', 'state_name', 'state_code', 'district_name', 'district_code', 'irrigated_area_type', 'area_classification', 'area_sub_classification', 'irrigated_area']

Soil:
['id', 'year', 'state_name', 'state_code', 'district_name', 'district_code', 'block_name', 'block_code', 'village_name', 'village_code', 'nutrient_type', 'nutrient_name', 'nutrient_level', 'value']